import { useEffect, useState } from "react";
import { BadgePercent, Megaphone, Users, Send, RefreshCw, Plus, Trash2, Upload, Ban } from "lucide-react";
import { toast } from "sonner";
import api, { formatApiErrorDetail } from "../lib/api";

const cls = "w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-2 text-sm text-slate-100 focus:outline-none focus:border-cyan-500/60";
const tabs = [["overview","Ringkasan"],["coupons","Kupon"],["campaigns","Kampanye"],["accounts","Akun Telegram"],["prospects","Prospek"],["groups","Posting Grup"],["results","Hasil"]];

export default function Promotions() {
  const [tab,setTab]=useState("overview"); const [summary,setSummary]=useState({}); const [coupons,setCoupons]=useState([]);
  const [accounts,setAccounts]=useState([]); const [prospects,setProspects]=useState([]); const [campaigns,setCampaigns]=useState([]);
  const [jobs,setJobs]=useState([]); const [groups,setGroups]=useState([]); const [results,setResults]=useState({}); const [sourceResults,setSourceResults]=useState([]);
  const [busy,setBusy]=useState(false);
  const [phone,setPhone]=useState(""); const [pending,setPending]=useState(""); const [otp,setOtp]=useState(""); const [twofa,setTwofa]=useState("");
  const [coupon,setCoupon]=useState({code:"",type:"percent",value:"",currency:"IDR",quota_total:"",per_user_limit:1,min_purchase:0,starts_at:"",ends_at:""});
  const [campaign,setCampaign]=useState({name:"",template:"",source_code:"",bot_link:"",account_ids:[],approval_required:true,daily_limit:20,min_interval_seconds:300,send_window_start:"09:00",send_window_end:"21:00"});
  const [post,setPost]=useState({account_id:"",group_id:"",message:""});

  const err=e=>toast.error(formatApiErrorDetail(e.response?.data?.detail)||"Terjadi kesalahan.");

  const load=async()=>{
    try {
      const [s,c,a,p,ca,j,g,res,sources]=await Promise.all([
        api.get("/admin/promo/summary"),api.get("/admin/promo/coupons"),api.get("/admin/promo/accounts"),
        api.get("/admin/promo/prospects"),api.get("/admin/promo/campaigns"),api.get("/admin/promo/jobs"),
        api.get("/admin/promo/groups"),api.get("/admin/promo/results"),api.get("/admin/promo/results/sources")
      ]);
      setSummary(s.data);setCoupons(c.data);setAccounts(a.data);setProspects(p.data);setCampaigns(ca.data);setJobs(j.data);setGroups(g.data);setResults(res.data);setSourceResults(sources.data);
    } catch(e){err(e)}
  };
  useEffect(()=>{load()},[]);

  const createCoupon=async()=>{
    if(!coupon.code.trim()||!Number(coupon.value)) return toast.error("Kode dan nilai kupon wajib diisi.");
    try { await api.post("/admin/promo/coupons",{...coupon,code:coupon.code.trim().toUpperCase(),value:Number(coupon.value),quota_total:coupon.quota_total?Number(coupon.quota_total):null,per_user_limit:Number(coupon.per_user_limit),min_purchase:Number(coupon.min_purchase||0),product_ids:[],starts_at:coupon.starts_at?new Date(coupon.starts_at).toISOString():null,ends_at:coupon.ends_at?new Date(coupon.ends_at).toISOString():null,active:true});toast.success("Kupon dibuat.");setCoupon({code:"",type:"percent",value:"",currency:"IDR",quota_total:"",per_user_limit:1,min_purchase:0,starts_at:"",ends_at:""});load(); } catch(e){err(e)}
  };
  const startLogin=async()=>{try{const r=await api.post("/admin/promo/accounts/login/start",{phone});setPending(r.data.account_id);toast.success("OTP dikirim.");}catch(e){err(e)}};
  const verifyLogin=async()=>{try{const r=await api.post("/admin/promo/accounts/login/"+pending+"/verify",{code:otp,password:twofa||null});if(r.data.status==="password_required")return toast.info("Masukkan password 2FA.");toast.success("Akun tersambung.");setPending("");setPhone("");setOtp("");setTwofa("");load();}catch(e){err(e)}};
  const revoke=async(id)=>{if(!confirm("Cabut session akun ini?"))return;try{await api.delete("/admin/promo/accounts/"+id);load()}catch(e){err(e)}};
  const importChats=async(id)=>{try{const r=await api.post("/admin/promo/accounts/"+id+"/import-private");toast.success("Import selesai: "+r.data.added+" prospek.");load()}catch(e){err(e)}};
  const syncGroups=async(id)=>{try{const r=await api.post("/admin/promo/accounts/"+id+"/sync-groups");toast.success("Grup tersinkron: "+r.data.groups);load()}catch(e){err(e)}};
  const createCampaign=async()=>{if(!campaign.name||!campaign.template)return toast.error("Nama dan template wajib diisi.");try{await api.post("/admin/promo/campaigns",campaign);toast.success("Campaign dibuat.");load()}catch(e){err(e)}};
  const enqueue=async(id)=>{try{const r=await api.post("/admin/promo/campaigns/"+id+"/enqueue");toast.success(r.data.queued+" job masuk antrean.");load()}catch(e){err(e)}};
  const approve=async(id)=>{try{await api.post("/admin/promo/jobs/"+id+"/approve");load()}catch(e){err(e)}};
  const stop=async(id)=>{try{await api.patch("/admin/promo/campaigns/"+id+"/stop");load()}catch(e){err(e)}};
  const optout=async(id)=>{try{await api.post("/admin/promo/opt-out",{tg_user_id:id,reason:"admin"});toast.success("Prospek masuk suppression list.");load()}catch(e){err(e)}};
  const postGroup=async()=>{try{await api.post("/admin/promo/groups/"+post.group_id+"/post",post);toast.success("Posting grup terkirim.");}catch(e){err(e)}};

  return <div className="space-y-5">
    <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={"px-4 py-2 rounded-lg text-sm whitespace-nowrap border "+(tab===id?"border-cyan-500/30 bg-cyan-500/10 text-cyan-300":"border-slate-800 text-slate-400")}>{label}</button>)}</div>

    {tab==="overview"&&<><div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[["Kupon",summary.coupons||0,BadgePercent],["Prospek",summary.prospects||0,Users],["Kampanye",summary.campaigns||0,Megaphone],["Akun Telegram",summary.telegram_accounts||0,Send],["Grup",summary.groups||0,Megaphone]].map(([l,v,I])=><div key={l} className="bg-slate-900/80 border border-slate-800 rounded-xl p-4"><I size={17} className="text-cyan-400 mb-3"/><p className="text-2xl font-semibold">{v}</p><p className="text-xs text-slate-500 mt-1">{l}</p></div>)}</div><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5"><h2 className="font-heading font-semibold">Promosi / Cari Pelanggan</h2><p className="text-sm text-slate-400 mt-2">Queue memakai approval, batas harian, jam pengiriman, suppression/opt-out, dan berhenti ketika Telegram memberikan pembatasan.</p></div></>}

    {tab==="accounts"&&<div className="space-y-5"><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3"><h2 className="font-semibold">Tambah Akun Telegram</h2><div className="grid md:grid-cols-3 gap-2"><input className={cls} placeholder="+628..." value={phone} onChange={e=>setPhone(e.target.value)}/><button onClick={startLogin} className="bg-cyan-600 rounded-lg">Kirim OTP</button><input className={cls} placeholder="OTP" value={otp} onChange={e=>setOtp(e.target.value)}/></div>{pending&&<div className="grid md:grid-cols-2 gap-2"><input className={cls} type="password" placeholder="Password 2FA jika diminta" value={twofa} onChange={e=>setTwofa(e.target.value)}/><button onClick={verifyLogin} className="bg-emerald-600 rounded-lg">Verifikasi</button></div>}</div><div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-800 text-xs text-slate-500"><th className="p-3 text-left">Akun</th><th className="p-3">Status</th><th className="p-3">Aksi</th></tr></thead><tbody>{accounts.map(a=><tr key={a._id} className="border-b border-slate-800/70"><td className="p-3">{a.name||a.username||a.tg_user_id}</td><td className="p-3">{a.status}</td><td className="p-3 flex gap-2 justify-center"><button onClick={()=>importChats(a._id)} title="Import private chat"><Upload size={15}/></button><button onClick={()=>syncGroups(a._id)}>Grup</button><button onClick={()=>revoke(a._id)} className="text-rose-400">Cabut</button></td></tr>)}</tbody></table></div></div>}

    {tab==="coupons"&&<div className="grid xl:grid-cols-[420px_1fr] gap-5"><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3"><h2 className="font-semibold">Buat Kupon</h2><input className={cls} placeholder="Kode" value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value})}/><div className="grid grid-cols-2 gap-2"><select className={cls} value={coupon.type} onChange={e=>setCoupon({...coupon,type:e.target.value})}><option value="percent">Persen</option><option value="fixed">Nominal</option></select><input className={cls} type="number" placeholder="Nilai" value={coupon.value} onChange={e=>setCoupon({...coupon,value:e.target.value})}/></div><div className="grid grid-cols-2 gap-2"><select className={cls} value={coupon.currency} onChange={e=>setCoupon({...coupon,currency:e.target.value})}><option>IDR</option><option>USD</option></select><input className={cls} type="number" placeholder="Limit / user" value={coupon.per_user_limit} onChange={e=>setCoupon({...coupon,per_user_limit:e.target.value})}/></div><input className={cls} type="number" placeholder="Kuota total" value={coupon.quota_total} onChange={e=>setCoupon({...coupon,quota_total:e.target.value})}/><input className={cls} type="number" placeholder="Minimum belanja" value={coupon.min_purchase} onChange={e=>setCoupon({...coupon,min_purchase:e.target.value})}/><button onClick={createCoupon} className="w-full bg-cyan-600 rounded-lg py-2">Buat Kupon</button></div><div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-slate-800"><th className="p-3 text-left">Kode</th><th>Pemakaian</th><th>Status</th></tr></thead><tbody>{coupons.map(c=><tr key={c._id} className="border-b border-slate-800/70"><td className="p-3 font-mono">{c.code}</td><td>{c.used_count||0}{c.quota_total==null?"":" / "+c.quota_total}</td><td>{c.active?"Aktif":"Nonaktif"}</td></tr>)}</tbody></table></div></div>}

    {tab==="campaigns"&&<div className="space-y-5"><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3"><h2 className="font-semibold">Campaign</h2><input className={cls} placeholder="Nama campaign" value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/><textarea className={cls} rows="5" placeholder="Pesan. Variabel: {nama} {username} {bot_link}" value={campaign.template} onChange={e=>setCampaign({...campaign,template:e.target.value})}/><div className="grid md:grid-cols-3 gap-2"><input className={cls} placeholder="Source code" value={campaign.source_code} onChange={e=>setCampaign({...campaign,source_code:e.target.value})}/><input className={cls} placeholder="Bot link" value={campaign.bot_link} onChange={e=>setCampaign({...campaign,bot_link:e.target.value})}/><input className={cls} type="number" min="1" value={campaign.daily_limit} onChange={e=>setCampaign({...campaign,daily_limit:Number(e.target.value)})}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={campaign.approval_required} onChange={e=>setCampaign({...campaign,approval_required:e.target.checked})}/> Perlu approval sebelum dikirim</label><button onClick={createCampaign} className="bg-cyan-600 rounded-lg px-4 py-2">Buat Campaign</button></div><div className="space-y-3">{campaigns.map(c=><div key={c._id} className="bg-slate-900/80 border border-slate-800 rounded-xl p-4 flex flex-wrap gap-3 items-center justify-between"><div><b>{c.name}</b><p className="text-xs text-slate-500">{c.status} · limit {c.daily_limit}/hari · interval ≥ {c.min_interval_seconds}s</p></div><div className="flex gap-2"><button onClick={()=>enqueue(c._id)} className="bg-cyan-700 px-3 py-2 rounded-lg text-sm">Buat Queue</button><button onClick={()=>stop(c._id)} className="bg-rose-700 px-3 py-2 rounded-lg text-sm">Stop</button></div></div>)}</div></div>}

    {tab==="prospects"&&<div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-x-auto"><div className="p-4 flex justify-between"><h2 className="font-semibold">Prospek</h2><button onClick={load}><RefreshCw size={15}/></button></div><table className="w-full text-sm"><thead><tr className="border-b border-slate-800 text-xs text-slate-500"><th className="p-3 text-left">Nama</th><th>Status</th><th>Username</th><th>Aksi</th></tr></thead><tbody>{prospects.map(p=><tr key={p._id} className="border-b border-slate-800/70"><td className="p-3">{p.name||"-"}</td><td>{p.status}</td><td>{p.username?"@"+p.username:"-"}</td><td><button onClick={()=>optout(p.tg_user_id)} className="text-rose-400"><Ban size={15}/></button></td></tr>)}</tbody></table></div>}

    {tab==="groups"&&<div className="space-y-5"><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5 space-y-3"><h2 className="font-semibold">Posting Grup — manual approval</h2><select className={cls} value={post.account_id} onChange={e=>setPost({...post,account_id:e.target.value})}><option value="">Pilih akun</option>{accounts.filter(a=>a.status==="active").map(a=><option key={a._id} value={a._id}>{a.name||a.username||a.tg_user_id}</option>)}</select><select className={cls} value={post.group_id} onChange={e=>setPost({...post,group_id:e.target.value})}><option value="">Pilih grup</option>{groups.map(g=><option key={g._id} value={g.chat_id}>{g.title}</option>)}</select><textarea className={cls} rows="5" placeholder="Pesan grup" value={post.message} onChange={e=>setPost({...post,message:e.target.value})}/><button onClick={postGroup} className="bg-cyan-600 rounded-lg py-2">Posting</button></div><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-4">{groups.length} grup tersinkron.</div></div>}

    {tab==="results"&&<div className="space-y-5"><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{Object.entries(results).map(([k,v])=><div key={k} className="bg-slate-900/80 border border-slate-800 rounded-xl p-5"><p className="text-2xl font-semibold">{v}</p><p className="text-xs text-slate-500 mt-1">{k}</p></div>)}</div><div className="bg-slate-900/80 border border-slate-800 rounded-xl p-5"><h2 className="font-semibold mb-3">Pembelian per Source</h2>{sourceResults.map(x=><div key={x._id} className="flex justify-between border-b border-slate-800 py-2 text-sm"><span>{x._id}</span><span>{x.orders} order · {x.revenue}</span></div>)}{!sourceResults.length&&<p className="text-sm text-slate-500">Belum ada transaksi beratribusi.</p>}</div></div>}

    {tab!=="overview"&&<div className="flex justify-end"><button onClick={load} className="text-slate-400 flex items-center gap-2"><RefreshCw size={15}/> Refresh</button></div>}
  </div>;
}